/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 393 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: __globinit_kraw_try1__globinit_kraw_try1^^efn^^
__globinit_kraw_try1(4248void);
extern 
void4168 ^^sfn^^: __CrestInit__CrestInit^^efn^^
__CrestInit(4248void) __attribute__((4360__crest_skip4360__)) ;
extern 
void4168 ^^sfn^^: __CrestHandleReturn__CrestHandleReturn^^efn^^
__CrestHandleReturn(4248int4176 ^z  , long long4176 ^z  ) __attribute__((4360__crest_skip4360__)) ;
extern 
void4168 ^^sfn^^: __CrestReturn__CrestReturn^^efn^^
__CrestReturn(4248int4176 ^z  ) __attribute__((4360__crest_skip4360__)) ;
extern 
void4168 ^^sfn^^: __CrestCall__CrestCall^^efn^^
__CrestCall(4248int4176 ^z  , unsigned int4176 ^z  ) __attribute__((4360__crest_skip4360__)) ;
extern 
void4168 ^^sfn^^: __CrestBranch__CrestBranch^^efn^^
__CrestBranch(4248int4176 ^z  , int4176 ^z  , unsigned char4176 ^z  ) __attribute__((4360__crest_skip4360__)) ;
extern 
void4168 ^^sfn^^: __CrestApply2__CrestApply2^^efn^^
__CrestApply2(4248int4176 ^z  , int4176 ^z  , long long4176 ^z  ) __attribute__((4360__crest_skip4360__)) ;
extern 
void4168 ^^sfn^^: __CrestApply1__CrestApply1^^efn^^
__CrestApply1(4248int4176 ^z  , int4176 ^z  , long long4176 ^z  ) __attribute__((4360__crest_skip4360__)) ;
extern 
void4168 ^^sfn^^: __CrestClearStack__CrestClearStack^^efn^^
__CrestClearStack(4248int4176 ^z  ) __attribute__((4360__crest_skip4360__)) ;
extern 
void4168 ^^sfn^^: __CrestStore__CrestStore^^efn^^
__CrestStore(4248int4176 ^z  , unsigned long4176 ^z  ) __attribute__((4360__crest_skip4360__)) ;
extern 
void4168 ^^sfn^^: __CrestLoad__CrestLoad^^efn^^
__CrestLoad(4248int4176 ^z  , unsigned long4176 ^z  , long long4176 ^z  ) __attribute__((4360__crest_skip4360__)) ;
#line 361 "/usr/include/stdio.h/usr/include/stdio.h*^YesMethod"
extern 
int4176 ^^sfn^^: printfprintf^^efn^^
printf(4248char const4461  4176 *4212 __restrict4461  ^z   , ...);
#line 7 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: foofoo^^efn^^
foo(4248double4182 ^z  )
{ DANSTART

  {
  __CrestCall(&*&1, &*&1END);

#line 7
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"%3.1f", &*&sum + 1.0END);
  __CrestClearStack(&*&2END);

  {
  __CrestReturn(&*&3END);
#line 7
  return;
  }
}
}
#line 8 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: foo2foo2^^efn^^
foo2(4248double4182 ^z  , double4182 ^z  )
{ DANSTART

  {
  __CrestCall(&*&4, &*&2END);

#line 8
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"%3.1f", &*&(sum + prod) + (3322double4182 )1END);
  __CrestClearStack(&*&5END);

  {
  __CrestReturn(&*&6END);
#line 8
  return;
  }
}
}
#line 9 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: foo3foo3^^efn^^
foo3(4248double4182 ^z  , double4182 ^z  , double4182 ^z  )
{ DANSTART

  {
  __CrestCall(&*&7, &*&3END);

#line 9
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"%3.1f", &*&(sum + prod) + tempEND);
  __CrestClearStack(&*&8END);

  {
  __CrestReturn(&*&9END);
#line 9
  return;
  }
}
}
#line 13 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

float4182 ^^sfn^^: Type1a_KrawitzType1a_Krawitz^^efn^^
Type1a_Krawitz(4248int4176 ^z  )
{ DANSTART
  int4176 p;#@#RV#@#
  
  int4176 sum;#@#RV#@#
  
  float4182 __retres4;#@#RV#@#

  {
  __CrestCall(&*&11, &*&4END);
  __CrestStore(&*&10, &*&(3322unsigned long4176 )(& n)END);
  __CrestLoad(&*&12, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )-1END);
  __CrestStore(&*&13, &*&(3322unsigned long4176 )(& p)END);
#line 15
  x = -1;
  __CrestLoad(&*&14, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&15, &*&(3322unsigned long4176 )(& sum)END);
#line 16
  x = 0;
  __CrestLoad(&*&16, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&17, &*&(3322unsigned long4176 )(& p)END);
#line 18
  x = 0;
  {
#line 18
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&20, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestLoad(&*&19, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&18, &*&16, &*&(3322long long4176 )(p < n)END);
#line 18
    if () {
      __CrestBranch(&*&21, &*&15, &*&1END);

    } else {
      __CrestBranch(&*&22, &*&16, &*&0END);
      goto while_x_break;
    }
    }
    __CrestLoad(&*&25, &*&(3322unsigned long4176 )(& sum), &*&(3322long long4176 )sumEND);
    __CrestLoad(&*&24, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestApply2(&*&23, &*&0, &*&(3322long long4176 )(sum + p)END);
    __CrestStore(&*&26, &*&(3322unsigned long4176 )(& sum)END);
#line 20
    x += p;
    __CrestLoad(&*&29, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestLoad(&*&28, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&27, &*&0, &*&(3322long long4176 )(p + 1)END);
    __CrestStore(&*&30, &*&(3322unsigned long4176 )(& p)END);
#line 18
    p ++;
  }
  while_x_break: /* CIL Label */ ;
  }
  {
  __CrestLoad(&*&33, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
  __CrestLoad(&*&32, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestApply2(&*&31, &*&12, &*&(3322long long4176 )(n == 0)END);
#line 23
  if () {
    __CrestBranch(&*&34, &*&20, &*&1END);
#line 23
    x = (3322float4182 )sum;
    goto return_label;
  } else {
    __CrestBranch(&*&35, &*&22, &*&0END);
#line 24
    x = (3322float4182 )(sum / n);
    goto return_label;
  }
  }
  return_label: /* CIL Label */ 
  {
  __CrestReturn(&*&36END);
#line 13
  return ();
  }
}
}
#line 28 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

int4176 ^^sfn^^: multmult^^efn^^
mult(4248int4176 ^z  , int4176 ^z  )
{ DANSTART
  int4176 __retres3;#@#RV#@#

  {
  __CrestCall(&*&39, &*&5END);
  __CrestStore(&*&38, &*&(3322unsigned long4176 )(& b)END);
  __CrestStore(&*&37, &*&(3322unsigned long4176 )(& a)END);
  __CrestLoad(&*&42, &*&(3322unsigned long4176 )(& a), &*&(3322long long4176 )aEND);
  __CrestLoad(&*&41, &*&(3322unsigned long4176 )(& b), &*&(3322long long4176 )bEND);
  __CrestApply2(&*&40, &*&2, &*&(3322long long4176 )(a * b)END);
  __CrestStore(&*&43, &*&(3322unsigned long4176 )(& __retres3)END);
#line 29
  x = a * b;
  {
  __CrestLoad(&*&44, &*&(3322unsigned long4176 )(& __retres3), &*&(3322long long4176 )__retres3END);
  __CrestReturn(&*&45END);
#line 28
  return ();
  }
}
}
#line 34 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

float4182 ^^sfn^^: Type1b_KrawitzType1b_Krawitz^^efn^^
Type1b_Krawitz(4248int4176 ^z  )
{ DANSTART
  int4176 p;#@#RV#@#
  
  int4176 sum;#@#RV#@#
  
  float4182 __retres4;#@#RV#@#

  {
  __CrestCall(&*&47, &*&6END);
  __CrestStore(&*&46, &*&(3322unsigned long4176 )(& n)END);
  __CrestLoad(&*&48, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )-1END);
  __CrestStore(&*&49, &*&(3322unsigned long4176 )(& p)END);
#line 36
  x = -1;
  __CrestLoad(&*&50, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&51, &*&(3322unsigned long4176 )(& sum)END);
#line 37
  x = 0;
  __CrestLoad(&*&52, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&53, &*&(3322unsigned long4176 )(& p)END);
#line 40
  x = 0;
  {
#line 40
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&56, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestLoad(&*&55, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&54, &*&16, &*&(3322long long4176 )(p < n)END);
#line 40
    if () {
      __CrestBranch(&*&57, &*&32, &*&1END);

    } else {
      __CrestBranch(&*&58, &*&33, &*&0END);
      goto while_x_break;
    }
    }
    __CrestLoad(&*&61, &*&(3322unsigned long4176 )(& sum), &*&(3322long long4176 )sumEND);
    __CrestLoad(&*&60, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestApply2(&*&59, &*&0, &*&(3322long long4176 )(sum + p)END);
    __CrestStore(&*&62, &*&(3322unsigned long4176 )(& sum)END);
#line 41
    x += p;
    __CrestLoad(&*&65, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestLoad(&*&64, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&63, &*&0, &*&(3322long long4176 )(p + 1)END);
    __CrestStore(&*&66, &*&(3322unsigned long4176 )(& p)END);
#line 40
    p ++;
  }
  while_x_break: /* CIL Label */ ;
  }
  {
  __CrestLoad(&*&69, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
  __CrestLoad(&*&68, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestApply2(&*&67, &*&12, &*&(3322long long4176 )(n == 0)END);
#line 43
  if () {
    __CrestBranch(&*&70, &*&37, &*&1END);
#line 44
    x = (3322float4182 )sum;
    goto return_label;
  } else {
    __CrestBranch(&*&71, &*&39, &*&0END);
#line 46
    x = (3322float4182 )(sum / n);
    goto return_label;
  }
  }
  return_label: /* CIL Label */ 
  {
  __CrestReturn(&*&72END);
#line 34
  return ();
  }
}
}
#line 53 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

float4182 ^^sfn^^: Type2a_KrawitzType2a_Krawitz^^efn^^
Type2a_Krawitz(4248int4176 ^z  )
{ DANSTART
  int4176 q;#@#RV#@#
  
  double4182 sum;#@#RV#@#
  
  float4182 __retres4;#@#RV#@#

  {
  __CrestCall(&*&74, &*&7END);
  __CrestStore(&*&73, &*&(3322unsigned long4176 )(& n)END);
  __CrestLoad(&*&75, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )-1END);
  __CrestStore(&*&76, &*&(3322unsigned long4176 )(& q)END);
#line 55
  x = -1;
#line 56
  x = (3322double4182 )0;
  __CrestLoad(&*&77, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&78, &*&(3322unsigned long4176 )(& q)END);
#line 58
  x = 0;
  {
#line 58
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&81, &*&(3322unsigned long4176 )(& q), &*&(3322long long4176 )qEND);
    __CrestLoad(&*&80, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&79, &*&16, &*&(3322long long4176 )(q < n)END);
#line 58
    if () {
      __CrestBranch(&*&82, &*&47, &*&1END);

    } else {
      __CrestBranch(&*&83, &*&48, &*&0END);
      goto while_x_break;
    }
    }
#line 60
    x += (3322double4182 )q;
    __CrestLoad(&*&86, &*&(3322unsigned long4176 )(& q), &*&(3322long long4176 )qEND);
    __CrestLoad(&*&85, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&84, &*&0, &*&(3322long long4176 )(q + 1)END);
    __CrestStore(&*&87, &*&(3322unsigned long4176 )(& q)END);
#line 58
    q ++;
  }
  while_x_break: /* CIL Label */ ;
  }
  {
  __CrestLoad(&*&90, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
  __CrestLoad(&*&89, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestApply2(&*&88, &*&12, &*&(3322long long4176 )(n == 0)END);
#line 63
  if () {
    __CrestBranch(&*&91, &*&52, &*&1END);
#line 63
    x = (3322float4182 )sum;
    goto return_label;
  } else {
    __CrestBranch(&*&92, &*&54, &*&0END);
#line 64
    x = (3322float4182 )(sum / (3322double4182 )n);
    goto return_label;
  }
  }
  return_label: /* CIL Label */ 
  {
  __CrestReturn(&*&93END);
#line 53
  return ();
  }
}
}
#line 68 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

float4182 ^^sfn^^: Type2b_KrawitzType2b_Krawitz^^efn^^
Type2b_Krawitz(4248int4176 ^z  )
{ DANSTART
  int4176 p;#@#RV#@#
  
  int4176 tot;#@#RV#@#
  
  float4182 __retres4;#@#RV#@#

  {
  __CrestCall(&*&95, &*&8END);
  __CrestStore(&*&94, &*&(3322unsigned long4176 )(& t)END);
  __CrestLoad(&*&96, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )-1END);
  __CrestStore(&*&97, &*&(3322unsigned long4176 )(& p)END);
#line 70
  x = -1;
  __CrestLoad(&*&98, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&99, &*&(3322unsigned long4176 )(& tot)END);
#line 71
  x = 0;
  __CrestLoad(&*&100, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&101, &*&(3322unsigned long4176 )(& p)END);
#line 74
  x = 0;
  {
#line 74
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&104, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestLoad(&*&103, &*&(3322unsigned long4176 )(& t), &*&(3322long long4176 )tEND);
    __CrestApply2(&*&102, &*&16, &*&(3322long long4176 )(p < t)END);
#line 74
    if () {
      __CrestBranch(&*&105, &*&62, &*&1END);

    } else {
      __CrestBranch(&*&106, &*&63, &*&0END);
      goto while_x_break;
    }
    }
    __CrestLoad(&*&109, &*&(3322unsigned long4176 )(& tot), &*&(3322long long4176 )totEND);
    __CrestLoad(&*&108, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestApply2(&*&107, &*&0, &*&(3322long long4176 )(tot + p)END);
    __CrestStore(&*&110, &*&(3322unsigned long4176 )(& tot)END);
#line 75
    x += p;
    __CrestLoad(&*&113, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestLoad(&*&112, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&111, &*&0, &*&(3322long long4176 )(p + 1)END);
    __CrestStore(&*&114, &*&(3322unsigned long4176 )(& p)END);
#line 74
    p ++;
  }
  while_x_break: /* CIL Label */ ;
  }
  {
  __CrestLoad(&*&117, &*&(3322unsigned long4176 )(& t), &*&(3322long long4176 )tEND);
  __CrestLoad(&*&116, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestApply2(&*&115, &*&12, &*&(3322long long4176 )(t == 0)END);
#line 77
  if () {
    __CrestBranch(&*&118, &*&67, &*&1END);
#line 78
    x = (3322float4182 )tot;
    goto return_label;
  } else {
    __CrestBranch(&*&119, &*&69, &*&0END);
#line 80
    x = (3322float4182 )(tot / t);
    goto return_label;
  }
  }
  return_label: /* CIL Label */ 
  {
  __CrestReturn(&*&120END);
#line 68
  return ();
  }
}
}
#line 85 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

float4182 ^^sfn^^: Type3a_KrawitzType3a_Krawitz^^efn^^
Type3a_Krawitz(4248int4176 ^z  )
{ DANSTART
  int4176 q;#@#RV#@#
  
  double4182 sum;#@#RV#@#
  
  float4182 __retres4;#@#RV#@#

  {
  __CrestCall(&*&122, &*&9END);
  __CrestStore(&*&121, &*&(3322unsigned long4176 )(& n)END);
  __CrestLoad(&*&123, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )-1END);
  __CrestStore(&*&124, &*&(3322unsigned long4176 )(& q)END);
#line 87
  x = -1;
#line 88
  x = (3322double4182 )0;
  __CrestLoad(&*&125, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&126, &*&(3322unsigned long4176 )(& q)END);
#line 90
  x = 0;
  {
#line 91
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&129, &*&(3322unsigned long4176 )(& q), &*&(3322long long4176 )qEND);
    __CrestLoad(&*&128, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&127, &*&16, &*&(3322long long4176 )(q < n)END);
#line 91
    if () {
      __CrestBranch(&*&130, &*&77, &*&1END);

    } else {
      __CrestBranch(&*&131, &*&78, &*&0END);
      goto while_x_break;
    }
    }
#line 93
    x += (3322double4182 )q;
    __CrestLoad(&*&134, &*&(3322unsigned long4176 )(& q), &*&(3322long long4176 )qEND);
    __CrestLoad(&*&133, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&132, &*&0, &*&(3322long long4176 )(q + 1)END);
    __CrestStore(&*&135, &*&(3322unsigned long4176 )(& q)END);
#line 94
    q ++;
  }
  while_x_break: /* CIL Label */ ;
  }
  {
  __CrestLoad(&*&138, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
  __CrestLoad(&*&137, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestApply2(&*&136, &*&12, &*&(3322long long4176 )(n == 0)END);
#line 97
  if () {
    __CrestBranch(&*&139, &*&82, &*&1END);
#line 97
    x = (3322float4182 )sum;
    goto return_label;
  } else {
    __CrestBranch(&*&140, &*&84, &*&0END);
#line 98
    x = (3322float4182 )(sum / (3322double4182 )n);
    goto return_label;
  }
  }
  return_label: /* CIL Label */ 
  {
  __CrestReturn(&*&141END);
#line 85
  return ();
  }
}
}
#line 102 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

float4182 ^^sfn^^: Type3b_KrawitzType3b_Krawitz^^efn^^
Type3b_Krawitz(4248int4176 ^z  )
{ DANSTART
  int4176 p;#@#RV#@#
  
  int4176 tot;#@#RV#@#
  
  float4182 __retres4;#@#RV#@#

  {
  __CrestCall(&*&143, &*&10END);
  __CrestStore(&*&142, &*&(3322unsigned long4176 )(& t)END);
  __CrestLoad(&*&144, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )-1END);
  __CrestStore(&*&145, &*&(3322unsigned long4176 )(& p)END);
#line 104
  x = -1;
  __CrestLoad(&*&146, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&147, &*&(3322unsigned long4176 )(& tot)END);
#line 104
  x = 0;
  __CrestLoad(&*&148, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&149, &*&(3322unsigned long4176 )(& p)END);
#line 107
  x = 0;
  {
#line 107
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&152, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestLoad(&*&151, &*&(3322unsigned long4176 )(& t), &*&(3322long long4176 )tEND);
    __CrestApply2(&*&150, &*&16, &*&(3322long long4176 )(p < t)END);
#line 107
    if () {
      __CrestBranch(&*&153, &*&92, &*&1END);

    } else {
      __CrestBranch(&*&154, &*&93, &*&0END);
      goto while_x_break;
    }
    }
    __CrestLoad(&*&157, &*&(3322unsigned long4176 )(& tot), &*&(3322long long4176 )totEND);
    __CrestLoad(&*&156, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestApply2(&*&155, &*&0, &*&(3322long long4176 )(tot + p)END);
    __CrestStore(&*&158, &*&(3322unsigned long4176 )(& tot)END);
#line 108
    x += p;
    __CrestLoad(&*&161, &*&(3322unsigned long4176 )(& p), &*&(3322long long4176 )pEND);
    __CrestLoad(&*&160, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&159, &*&0, &*&(3322long long4176 )(p + 1)END);
    __CrestStore(&*&162, &*&(3322unsigned long4176 )(& p)END);
#line 107
    p ++;
  }
  while_x_break: /* CIL Label */ ;
  }
  {
  __CrestLoad(&*&165, &*&(3322unsigned long4176 )(& t), &*&(3322long long4176 )tEND);
  __CrestLoad(&*&164, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestApply2(&*&163, &*&12, &*&(3322long long4176 )(t == 0)END);
#line 110
  if () {
    __CrestBranch(&*&166, &*&97, &*&1END);
#line 111
    x = (3322float4182 )((3322double4182 )tot);
    goto return_label;
  } else {
    __CrestBranch(&*&167, &*&99, &*&0END);
#line 113
    x = (3322float4182 )((3322double4182 )tot / (3322double4182 )t);
    goto return_label;
  }
  }
  return_label: /* CIL Label */ 
  {
  __CrestReturn(&*&168END);
#line 102
  return ();
  }
}
}
#line 126
extern 
int4176 ^^sfn^^: mallocmalloc^^efn^^
(4243 /* missing proto */4461  malloc)(4248);
#line 133
extern 
int4176 ^^sfn^^: freefree^^efn^^
(4243 /* missing proto */4461  free)(4248);
#line 118 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

double4182 ^^sfn^^: Type4a_KrawitzType4a_Krawitz^^efn^^
Type4a_Krawitz(4248int4176 ^z  )
{ DANSTART
  double4182 *4212d;#@#RV#@#
  
  double4182 tot;#@#RV#@#
  
  int4176 n;#@#RV#@#
  
  int4176 tmp;#@#RV#@#
  
  double4182 *4212mem_6;#@#RV#@#
  
  double4182 *4212mem_7;#@#RV#@#

  {
  __CrestCall(&*&170, &*&11END);
  __CrestStore(&*&169, &*&(3322unsigned long4176 )(& limit)END);
#line 120
  x = (3322double4182 )0;
  {
  __CrestLoad(&*&173, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
  __CrestLoad(&*&172, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1000END);
  __CrestApply2(&*&171, &*&14, &*&(3322long long4176 )(limit > 1000)END);
#line 123
  if () {
    __CrestBranch(&*&174, &*&104, &*&1END);
    __CrestLoad(&*&176, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestStore(&*&177, &*&(3322unsigned long4176 )(& limit)END);
#line 124
    x = 1;
  } else {
    __CrestBranch(&*&175, &*&105, &*&0END);
    {
    __CrestLoad(&*&180, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
    __CrestLoad(&*&179, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&178, &*&16, &*&(3322long long4176 )(limit < 1)END);
#line 123
    if () {
      __CrestBranch(&*&181, &*&106, &*&1END);
      __CrestLoad(&*&183, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
      __CrestStore(&*&184, &*&(3322unsigned long4176 )(& limit)END);
#line 124
      x = 1;
    } else {
      __CrestBranch(&*&182, &*&107, &*&0END);

    }
    }
  }
  }
  __CrestLoad(&*&187, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
  __CrestLoad(&*&186, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )sizeof(double4182 )END);
  __CrestApply2(&*&185, &*&2, &*&(3322long long4176 )((3322unsigned long4176 )limit * sizeof(double4182 ))END);
#line 126
  tmp3588 = malloc(&*&(3322unsigned long4176 )limit * sizeof(double4182 )END);
  __CrestHandleReturn(&*&189, &*&(3322long long4176 )tmpEND);
  __CrestStore(&*&188, &*&(3322unsigned long4176 )(& tmp)END);
#line 126
  x = (3322double4182 *4212)tmp;
  __CrestLoad(&*&190, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&191, &*&(3322unsigned long4176 )(& n)END);
#line 128
  x = 0;
  {
#line 128
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&194, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestLoad(&*&193, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
    __CrestApply2(&*&192, &*&16, &*&(3322long long4176 )(n < limit)END);
#line 128
    if () {
      __CrestBranch(&*&195, &*&113, &*&1END);

    } else {
      __CrestBranch(&*&196, &*&114, &*&0END);
      goto while_x_break;
    }
    }
#line 129
    x = d + n;
#line 129
    x = (3322double4182 )((n * n) * n);
    __CrestLoad(&*&199, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestLoad(&*&198, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&197, &*&0, &*&(3322long long4176 )(n + 1)END);
    __CrestStore(&*&200, &*&(3322unsigned long4176 )(& n)END);
#line 128
    n ++;
  }
  while_x_break: /* CIL Label */ ;
  }
  __CrestLoad(&*&201, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&202, &*&(3322unsigned long4176 )(& n)END);
#line 131
  x = 0;
  {
#line 131
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&205, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestLoad(&*&204, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
    __CrestApply2(&*&203, &*&16, &*&(3322long long4176 )(n < limit)END);
#line 131
    if () {
      __CrestBranch(&*&206, &*&122, &*&1END);

    } else {
      __CrestBranch(&*&207, &*&123, &*&0END);
      goto while_x_break;
    }
    }
#line 132
    x = d + n;
#line 132
    x += *3284mem_7;
    __CrestLoad(&*&210, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestLoad(&*&209, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&208, &*&0, &*&(3322long long4176 )(n + 1)END);
    __CrestStore(&*&211, &*&(3322unsigned long4176 )(& n)END);
#line 131
    n ++;
  }
  while_x_break: /* CIL Label */ ;
  }
#line 133
  free(&*&(3322void4168 *4212)dEND);
  __CrestClearStack(&*&212END);
  {
  __CrestReturn(&*&213END);
#line 134
  return ();
  }
}
}
#line 139 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

double4182 ^^sfn^^: Type4b2_KrawitzType4b2_Krawitz^^efn^^
Type4b2_Krawitz(4248char4176 ^z  , int4176 ^z  , double4182 ^z  , int4176 ^z  )
{ DANSTART

  {
  __CrestCall(&*&217, &*&12END);
  __CrestStore(&*&216, &*&(3322unsigned long4176 )(& n)END);
  __CrestStore(&*&215, &*&(3322unsigned long4176 )(& limit)END);
  __CrestStore(&*&214, &*&(3322unsigned long4176 )(& s)END);
  {
  __CrestLoad(&*&220, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
  __CrestLoad(&*&219, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1000END);
  __CrestApply2(&*&218, &*&14, &*&(3322long long4176 )(limit > 1000)END);
#line 142
  if () {
    __CrestBranch(&*&221, &*&129, &*&1END);
    __CrestLoad(&*&223, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1000END);
    __CrestStore(&*&224, &*&(3322unsigned long4176 )(& limit)END);
#line 143
    x = 1000;
  } else {
    __CrestBranch(&*&222, &*&130, &*&0END);
    {
    __CrestLoad(&*&227, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
    __CrestLoad(&*&226, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&225, &*&16, &*&(3322long long4176 )(limit < 1)END);
#line 142
    if () {
      __CrestBranch(&*&228, &*&131, &*&1END);
      __CrestLoad(&*&230, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1000END);
      __CrestStore(&*&231, &*&(3322unsigned long4176 )(& limit)END);
#line 143
      x = 1000;
    } else {
      __CrestBranch(&*&229, &*&132, &*&0END);

    }
    }
  }
  }
  {
  __CrestLoad(&*&234, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
  __CrestLoad(&*&233, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
  __CrestApply2(&*&232, &*&16, &*&(3322long long4176 )(n < limit)END);
#line 145
  if () {
    __CrestBranch(&*&235, &*&134, &*&1END);
    __CrestLoad(&*&239, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestLoad(&*&238, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&237, &*&0, &*&(3322long long4176 )(n + 1)END);
    __CrestStore(&*&240, &*&(3322unsigned long4176 )(& n)END);
#line 146
    n ++;
    __CrestLoad(&*&241, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )((3322char4176 )'-')END);
    __CrestLoad(&*&242, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
    __CrestLoad(&*&243, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
#line 146
    tot3588 = Type4b2_Krawitz(&*&(3322char4176 )'-', &*&limit, &*&tot + (3322double4182 )((n * n) * n),
                                 &*&nEND);
    __CrestClearStack(&*&244END);
  } else {
    __CrestBranch(&*&236, &*&135, &*&0END);

  }
  }
  {
  __CrestReturn(&*&245END);
#line 148
  return ();
  }
}
}
#line 152 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

double4182 ^^sfn^^: Type4b_KrawitzType4b_Krawitz^^efn^^
Type4b_Krawitz(4248int4176 ^z  )
{ DANSTART
  double4182 tmp;#@#RV#@#

  {
  __CrestCall(&*&247, &*&13END);
  __CrestStore(&*&246, &*&(3322unsigned long4176 )(& limit)END);
  {
  __CrestLoad(&*&250, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
  __CrestLoad(&*&249, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1000END);
  __CrestApply2(&*&248, &*&14, &*&(3322long long4176 )(limit > 1000)END);
#line 155
  if () {
    __CrestBranch(&*&251, &*&138, &*&1END);
    __CrestLoad(&*&253, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1000END);
    __CrestStore(&*&254, &*&(3322unsigned long4176 )(& limit)END);
#line 156
    x = 1000;
  } else {
    __CrestBranch(&*&252, &*&139, &*&0END);
    {
    __CrestLoad(&*&257, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
    __CrestLoad(&*&256, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&255, &*&16, &*&(3322long long4176 )(limit < 1)END);
#line 155
    if () {
      __CrestBranch(&*&258, &*&140, &*&1END);
      __CrestLoad(&*&260, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1000END);
      __CrestStore(&*&261, &*&(3322unsigned long4176 )(& limit)END);
#line 156
      x = 1000;
    } else {
      __CrestBranch(&*&259, &*&141, &*&0END);

    }
    }
  }
  }
  __CrestLoad(&*&262, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )((3322char4176 )'-')END);
  __CrestLoad(&*&263, &*&(3322unsigned long4176 )(& limit), &*&(3322long long4176 )limitEND);
  __CrestLoad(&*&264, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
#line 158
  tmp3588 = Type4b2_Krawitz(&*&(3322char4176 )'-', &*&limit, &*&(3322double4182 )0,
                               &*&0END);
  __CrestClearStack(&*&265END);
  {
  __CrestReturn(&*&266END);
#line 158
  return ();
  }
}
}
#line 165 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProdOsumProdO^^efn^^
sumProdO(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&268, &*&14END);
  __CrestStore(&*&267, &*&(3322unsigned long4176 )(& n)END);
#line 166
  x = 0.0;
#line 167
  x = 1.0;
  __CrestLoad(&*&269, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&270, &*&(3322unsigned long4176 )(& i)END);
#line 169
  x = 1;
  {
#line 169
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&273, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&272, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&271, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 169
    if () {
      __CrestBranch(&*&274, &*&149, &*&1END);

    } else {
      __CrestBranch(&*&275, &*&150, &*&0END);
      goto while_x_break;
    }
    }
#line 171
    x += (3322double4182 )i;
#line 172
    x *= (3322double4182 )i;
#line 173
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&276END);
    __CrestLoad(&*&279, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&278, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&277, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&280, &*&(3322unsigned long4176 )(& i)END);
#line 169
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&281END);
#line 165
  return;
  }
}
}
#line 178 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd1AsumProd1A^^efn^^
sumProd1A(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&283, &*&15END);
  __CrestStore(&*&282, &*&(3322unsigned long4176 )(& n)END);
#line 179
  x = 0.0;
#line 180
  x = 1.0;
  __CrestLoad(&*&284, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&285, &*&(3322unsigned long4176 )(& i)END);
#line 182
  x = 1;
  {
#line 182
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&288, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&287, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&286, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 182
    if () {
      __CrestBranch(&*&289, &*&160, &*&1END);

    } else {
      __CrestBranch(&*&290, &*&161, &*&0END);
      goto while_x_break;
    }
    }
#line 184
    x += (3322double4182 )i;
#line 185
    x *= (3322double4182 )i;
#line 186
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&291END);
    __CrestLoad(&*&294, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&293, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&292, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&295, &*&(3322unsigned long4176 )(& i)END);
#line 182
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&296END);
#line 178
  return;
  }
}
}
#line 191 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd1BsumProd1B^^efn^^
sumProd1B(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&298, &*&16END);
  __CrestStore(&*&297, &*&(3322unsigned long4176 )(& n)END);
#line 192
  x = 0.0;
#line 193
  x = 1.0;
  __CrestLoad(&*&299, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&300, &*&(3322unsigned long4176 )(& i)END);
#line 195
  x = 1;
  {
#line 195
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&303, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&302, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&301, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 195
    if () {
      __CrestBranch(&*&304, &*&171, &*&1END);

    } else {
      __CrestBranch(&*&305, &*&172, &*&0END);
      goto while_x_break;
    }
    }
#line 197
    x += (3322double4182 )i;
#line 198
    x *= (3322double4182 )i;
#line 199
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&306END);
    __CrestLoad(&*&309, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&308, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&307, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&310, &*&(3322unsigned long4176 )(& i)END);
#line 195
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&311END);
#line 191
  return;
  }
}
}
#line 204 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd1CsumProd1C^^efn^^
sumProd1C(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&313, &*&17END);
  __CrestStore(&*&312, &*&(3322unsigned long4176 )(& n)END);
#line 205
  x = 0.0;
#line 206
  x = 1.0;
  __CrestLoad(&*&314, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&315, &*&(3322unsigned long4176 )(& i)END);
#line 208
  x = 1;
  {
#line 208
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&318, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&317, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&316, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 208
    if () {
      __CrestBranch(&*&319, &*&182, &*&1END);

    } else {
      __CrestBranch(&*&320, &*&183, &*&0END);
      goto while_x_break;
    }
    }
#line 210
    x += (3322double4182 )i;
#line 211
    x *= (3322double4182 )i;
#line 212
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&321END);
    __CrestLoad(&*&324, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&323, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&322, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&325, &*&(3322unsigned long4176 )(& i)END);
#line 208
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&326END);
#line 204
  return;
  }
}
}
#line 217 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd2AsumProd2A^^efn^^
sumProd2A(4248int4176 ^z  )
{ DANSTART
  double4182 s;#@#RV#@#
  
  double4182 p;#@#RV#@#
  
  int4176 j;#@#RV#@#

  {
  __CrestCall(&*&328, &*&18END);
  __CrestStore(&*&327, &*&(3322unsigned long4176 )(& n)END);
#line 218
  x = 0.0;
#line 219
  x = 1.0;
  __CrestLoad(&*&329, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&330, &*&(3322unsigned long4176 )(& j)END);
#line 221
  x = 1;
  {
#line 221
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&333, &*&(3322unsigned long4176 )(& j), &*&(3322long long4176 )jEND);
    __CrestLoad(&*&332, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&331, &*&15, &*&(3322long long4176 )(j <= n)END);
#line 221
    if () {
      __CrestBranch(&*&334, &*&193, &*&1END);

    } else {
      __CrestBranch(&*&335, &*&194, &*&0END);
      goto while_x_break;
    }
    }
#line 223
    x += (3322double4182 )j;
#line 224
    x *= (3322double4182 )j;
#line 225
    foo2(&*&s, &*&pEND);
    __CrestClearStack(&*&336END);
    __CrestLoad(&*&339, &*&(3322unsigned long4176 )(& j), &*&(3322long long4176 )jEND);
    __CrestLoad(&*&338, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&337, &*&0, &*&(3322long long4176 )(j + 1)END);
    __CrestStore(&*&340, &*&(3322unsigned long4176 )(& j)END);
#line 221
    j ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&341END);
#line 217
  return;
  }
}
}
#line 230 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd2BsumProd2B^^efn^^
sumProd2B(4248int4176 ^z  )
{ DANSTART
  double4182 s;#@#RV#@#
  
  double4182 p;#@#RV#@#
  
  int4176 j;#@#RV#@#

  {
  __CrestCall(&*&343, &*&19END);
  __CrestStore(&*&342, &*&(3322unsigned long4176 )(& n)END);
#line 231
  x = 0.0;
#line 232
  x = 1.0;
  __CrestLoad(&*&344, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&345, &*&(3322unsigned long4176 )(& j)END);
#line 234
  x = 1;
  {
#line 234
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&348, &*&(3322unsigned long4176 )(& j), &*&(3322long long4176 )jEND);
    __CrestLoad(&*&347, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&346, &*&15, &*&(3322long long4176 )(j <= n)END);
#line 234
    if () {
      __CrestBranch(&*&349, &*&204, &*&1END);

    } else {
      __CrestBranch(&*&350, &*&205, &*&0END);
      goto while_x_break;
    }
    }
#line 236
    x += (3322double4182 )j;
#line 237
    x *= (3322double4182 )j;
#line 238
    foo2(&*&p, &*&sEND);
    __CrestClearStack(&*&351END);
    __CrestLoad(&*&354, &*&(3322unsigned long4176 )(& j), &*&(3322long long4176 )jEND);
    __CrestLoad(&*&353, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&352, &*&0, &*&(3322long long4176 )(j + 1)END);
    __CrestStore(&*&355, &*&(3322unsigned long4176 )(& j)END);
#line 234
    j ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&356END);
#line 230
  return;
  }
}
}
#line 243 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd2CsumProd2C^^efn^^
sumProd2C(4248int4176 ^z  )
{ DANSTART
  int4176 sum;#@#RV#@#
  
  int4176 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&358, &*&20END);
  __CrestStore(&*&357, &*&(3322unsigned long4176 )(& n)END);
  __CrestLoad(&*&359, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&360, &*&(3322unsigned long4176 )(& sum)END);
#line 244
  x = 0;
  __CrestLoad(&*&361, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&362, &*&(3322unsigned long4176 )(& prod)END);
#line 245
  x = 1;
  __CrestLoad(&*&363, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&364, &*&(3322unsigned long4176 )(& i)END);
#line 247
  x = 1;
  {
#line 247
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&367, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&366, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&365, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 247
    if () {
      __CrestBranch(&*&368, &*&215, &*&1END);

    } else {
      __CrestBranch(&*&369, &*&216, &*&0END);
      goto while_x_break;
    }
    }
    __CrestLoad(&*&372, &*&(3322unsigned long4176 )(& sum), &*&(3322long long4176 )sumEND);
    __CrestLoad(&*&371, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestApply2(&*&370, &*&0, &*&(3322long long4176 )(sum + i)END);
    __CrestStore(&*&373, &*&(3322unsigned long4176 )(& sum)END);
#line 249
    x += i;
    __CrestLoad(&*&376, &*&(3322unsigned long4176 )(& prod), &*&(3322long long4176 )prodEND);
    __CrestLoad(&*&375, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestApply2(&*&374, &*&2, &*&(3322long long4176 )(prod * i)END);
    __CrestStore(&*&377, &*&(3322unsigned long4176 )(& prod)END);
#line 250
    x *= i;
#line 251
    foo2(&*&(3322double4182 )sum, &*&(3322double4182 )prodEND);
    __CrestClearStack(&*&378END);
    __CrestLoad(&*&381, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&380, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&379, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&382, &*&(3322unsigned long4176 )(& i)END);
#line 247
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&383END);
#line 243
  return;
  }
}
}
#line 256 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd2DsumProd2D^^efn^^
sumProd2D(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&385, &*&21END);
  __CrestStore(&*&384, &*&(3322unsigned long4176 )(& n)END);
#line 257
  x = 0.0;
#line 258
  x = 1.0;
  __CrestLoad(&*&386, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&387, &*&(3322unsigned long4176 )(& i)END);
#line 260
  x = 1;
  {
#line 260
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&390, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&389, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&388, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 260
    if () {
      __CrestBranch(&*&391, &*&226, &*&1END);

    } else {
      __CrestBranch(&*&392, &*&227, &*&0END);
      goto while_x_break;
    }
    }
#line 262
    x += (3322double4182 )(i * i);
#line 263
    x *= (3322double4182 )(i * i);
#line 264
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&393END);
    __CrestLoad(&*&396, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&395, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&394, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&397, &*&(3322unsigned long4176 )(& i)END);
#line 260
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&398END);
#line 256
  return;
  }
}
}
#line 269 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd3AsumProd3A^^efn^^
sumProd3A(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&400, &*&22END);
  __CrestStore(&*&399, &*&(3322unsigned long4176 )(& n)END);
#line 270
  x = 0.0;
#line 271
  x = 1.0;
  __CrestLoad(&*&401, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&402, &*&(3322unsigned long4176 )(& i)END);
#line 273
  x = 1;
  {
#line 273
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&405, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&404, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&403, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 273
    if () {
      __CrestBranch(&*&406, &*&237, &*&1END);

    } else {
      __CrestBranch(&*&407, &*&238, &*&0END);
      goto while_x_break;
    }
    }
#line 275
    x += (3322double4182 )i;
#line 276
    x *= (3322double4182 )i;
#line 277
    foo3(&*&sum, &*&prod, &*&(3322double4182 )nEND);
    __CrestClearStack(&*&408END);
    __CrestLoad(&*&411, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&410, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&409, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&412, &*&(3322unsigned long4176 )(& i)END);
#line 273
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&413END);
#line 269
  return;
  }
}
}
#line 282 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd3BsumProd3B^^efn^^
sumProd3B(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&415, &*&23END);
  __CrestStore(&*&414, &*&(3322unsigned long4176 )(& n)END);
#line 283
  x = 0.0;
#line 284
  x = 1.0;
  __CrestLoad(&*&416, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&417, &*&(3322unsigned long4176 )(& i)END);
#line 286
  x = 1;
  {
#line 286
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&420, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&419, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&418, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 286
    if () {
      __CrestBranch(&*&421, &*&248, &*&1END);

    } else {
      __CrestBranch(&*&422, &*&249, &*&0END);
      goto while_x_break;
    }
    }
#line 288
    x += (3322double4182 )i;
#line 289
    x *= (3322double4182 )i;
#line 290
    foo(&*&prodEND);
    __CrestClearStack(&*&423END);
    __CrestLoad(&*&426, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&425, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&424, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&427, &*&(3322unsigned long4176 )(& i)END);
#line 286
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&428END);
#line 282
  return;
  }
}
}
#line 295 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd3CsumProd3C^^efn^^
sumProd3C(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&430, &*&24END);
  __CrestStore(&*&429, &*&(3322unsigned long4176 )(& n)END);
#line 296
  x = 0.0;
#line 297
  x = 1.0;
  __CrestLoad(&*&431, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&432, &*&(3322unsigned long4176 )(& i)END);
#line 299
  x = 1;
  {
#line 299
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&435, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&434, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&433, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 299
    if () {
      __CrestBranch(&*&436, &*&259, &*&1END);

    } else {
      __CrestBranch(&*&437, &*&260, &*&0END);
      goto while_x_break;
    }
    }
#line 301
    x += (3322double4182 )i;
#line 302
    x *= (3322double4182 )i;
    {
    __CrestLoad(&*&442, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestLoad(&*&441, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )2END);
    __CrestApply2(&*&440, &*&4, &*&(3322long long4176 )(n % 2)END);
    __CrestLoad(&*&439, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
    __CrestApply2(&*&438, &*&12, &*&(3322long long4176 )(n % 2 == 0)END);
#line 303
    if () {
      __CrestBranch(&*&443, &*&263, &*&1END);
#line 304
      foo2(&*&sum, &*&prodEND);
      __CrestClearStack(&*&445END);
    } else {
      __CrestBranch(&*&444, &*&264, &*&0END);

    }
    }
    __CrestLoad(&*&448, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&447, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&446, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&449, &*&(3322unsigned long4176 )(& i)END);
#line 299
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&450END);
#line 295
  return;
  }
}
}
#line 310 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd3DsumProd3D^^efn^^
sumProd3D(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&452, &*&25END);
  __CrestStore(&*&451, &*&(3322unsigned long4176 )(& n)END);
#line 311
  x = 0.0;
#line 312
  x = 1.0;
  __CrestLoad(&*&453, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&454, &*&(3322unsigned long4176 )(& i)END);
#line 314
  x = 1;
  {
#line 314
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&457, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&456, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&455, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 314
    if () {
      __CrestBranch(&*&458, &*&274, &*&1END);

    } else {
      __CrestBranch(&*&459, &*&275, &*&0END);
      goto while_x_break;
    }
    }
#line 316
    x += (3322double4182 )i;
#line 318
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&460END);
    __CrestLoad(&*&463, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&462, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&461, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&464, &*&(3322unsigned long4176 )(& i)END);
#line 314
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&465END);
#line 310
  return;
  }
}
}
#line 324 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd3EsumProd3E^^efn^^
sumProd3E(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&467, &*&26END);
  __CrestStore(&*&466, &*&(3322unsigned long4176 )(& n)END);
#line 325
  x = 0.0;
#line 326
  x = 1.0;
  __CrestLoad(&*&468, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&469, &*&(3322unsigned long4176 )(& i)END);
#line 328
  x = 1;
  {
#line 328
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&472, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&471, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&470, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 328
    if () {
      __CrestBranch(&*&473, &*&285, &*&1END);

    } else {
      __CrestBranch(&*&474, &*&286, &*&0END);
      goto while_x_break;
    }
    }
    {
    __CrestLoad(&*&479, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&478, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )2END);
    __CrestApply2(&*&477, &*&4, &*&(3322long long4176 )(i % 2)END);
    __CrestLoad(&*&476, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
    __CrestApply2(&*&475, &*&12, &*&(3322long long4176 )(i % 2 == 0)END);
#line 330
    if () {
      __CrestBranch(&*&480, &*&288, &*&1END);
#line 332
      x += (3322double4182 )i;
    } else {
      __CrestBranch(&*&481, &*&289, &*&0END);

    }
    }
#line 334
    x *= (3322double4182 )i;
#line 335
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&482END);
    __CrestLoad(&*&485, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&484, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&483, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&486, &*&(3322unsigned long4176 )(& i)END);
#line 328
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&487END);
#line 324
  return;
  }
}
}
#line 340 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd4AsumProd4A^^efn^^
sumProd4A(4248int4176 ^z  )
{ DANSTART
  double4182 prod;#@#RV#@#
  
  double4182 sum;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&489, &*&27END);
  __CrestStore(&*&488, &*&(3322unsigned long4176 )(& n)END);
#line 341
  x = 1.0;
#line 342
  x = 0.0;
  __CrestLoad(&*&490, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&491, &*&(3322unsigned long4176 )(& i)END);
#line 344
  x = 1;
  {
#line 344
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&494, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&493, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&492, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 344
    if () {
      __CrestBranch(&*&495, &*&299, &*&1END);

    } else {
      __CrestBranch(&*&496, &*&300, &*&0END);
      goto while_x_break;
    }
    }
#line 346
    x += (3322double4182 )i;
#line 347
    x *= (3322double4182 )i;
#line 348
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&497END);
    __CrestLoad(&*&500, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&499, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&498, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&501, &*&(3322unsigned long4176 )(& i)END);
#line 344
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&502END);
#line 340
  return;
  }
}
}
#line 353 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd4BsumProd4B^^efn^^
sumProd4B(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&504, &*&28END);
  __CrestStore(&*&503, &*&(3322unsigned long4176 )(& n)END);
#line 354
  x = 0.0;
#line 355
  x = 1.0;
  __CrestLoad(&*&505, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&506, &*&(3322unsigned long4176 )(& i)END);
#line 357
  x = 1;
  {
#line 357
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&509, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&508, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&507, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 357
    if () {
      __CrestBranch(&*&510, &*&310, &*&1END);

    } else {
      __CrestBranch(&*&511, &*&311, &*&0END);
      goto while_x_break;
    }
    }
#line 359
    x *= (3322double4182 )i;
#line 360
    x += (3322double4182 )i;
#line 361
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&512END);
    __CrestLoad(&*&515, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&514, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&513, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&516, &*&(3322unsigned long4176 )(& i)END);
#line 357
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&517END);
#line 353
  return;
  }
}
}
#line 366 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd4CsumProd4C^^efn^^
sumProd4C(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&519, &*&29END);
  __CrestStore(&*&518, &*&(3322unsigned long4176 )(& n)END);
#line 367
  x = 0.0;
#line 368
  x = 1.0;
  __CrestLoad(&*&520, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
  __CrestStore(&*&521, &*&(3322unsigned long4176 )(& i)END);
#line 370
  x = 1;
  {
#line 370
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&524, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&523, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&522, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 370
    if () {
      __CrestBranch(&*&525, &*&321, &*&1END);

    } else {
      __CrestBranch(&*&526, &*&322, &*&0END);
      goto while_x_break;
    }
    }
#line 372
    x += (3322double4182 )i;
#line 373
    foo2(&*&sum, &*&prodEND);
    __CrestClearStack(&*&527END);
#line 374
    x *= (3322double4182 )i;
    __CrestLoad(&*&530, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&529, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )1END);
    __CrestApply2(&*&528, &*&0, &*&(3322long long4176 )(i + 1)END);
    __CrestStore(&*&531, &*&(3322unsigned long4176 )(& i)END);
#line 370
    i ++;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&532END);
#line 366
  return;
  }
}
}
#line 379 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: sumProd4DsumProd4D^^efn^^
sumProd4D(4248int4176 ^z  )
{ DANSTART
  double4182 sum;#@#RV#@#
  
  double4182 prod;#@#RV#@#
  
  int4176 i;#@#RV#@#

  {
  __CrestCall(&*&534, &*&30END);
  __CrestStore(&*&533, &*&(3322unsigned long4176 )(& n)END);
#line 380
  x = 0.0;
#line 381
  x = 1.0;
  __CrestLoad(&*&535, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )0END);
  __CrestStore(&*&536, &*&(3322unsigned long4176 )(& i)END);
#line 382
  x = 0;
  {
#line 383
  while (1) {
    while_x_continue: /* CIL Label */ ;
    {
    __CrestLoad(&*&539, &*&(3322unsigned long4176 )(& i), &*&(3322long long4176 )iEND);
    __CrestLoad(&*&538, &*&(3322unsigned long4176 )(& n), &*&(3322long long4176 )nEND);
    __CrestApply2(&*&537, &*&15, &*&(3322long long4176 )(i <= n)END);
#line 383
    if () {
      __CrestBranch(&*&540, &*&332, &*&1END);

    } else {
      __CrestBranch(&*&541, &*&333, &*&0END);
      goto while_x_break;
    }
    }
#line 385
    x += (3322double4182 )i;
#line 386
    x *= (3322double4182 )i;
  }
  while_x_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(&*&542END);
#line 379
  return;
  }
}
}
#line 454
extern 
int4176 ^^sfn^^: systemsystem^^efn^^
(4243 /* missing proto */4461  system)(4248);
#line 393 "../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c../sourceFiles/scriptoutput/kraw_copy/kraw_try1.c*^YesMethod"

void4168 ^^sfn^^: mainmain^^efn^^
main(4248void)
{ DANSTART
  int4176 tmp;#@#RV#@#
  
  float4182 tmp___0;#@#RV#@#
  
  float4182 tmp___1;#@#RV#@#
  
  float4182 tmp___2;#@#RV#@#
  
  float4182 tmp___3;#@#RV#@#
  
  float4182 tmp___4;#@#RV#@#
  
  float4182 tmp___5;#@#RV#@#
  
  double4182 tmp___6;#@#RV#@#
  
  double4182 tmp___7;#@#RV#@#
  
  double4182 tmp___8;#@#RV#@#

  {
  __globinit_kraw_try1(&*&END);
  __CrestCall(&*&543, &*&31END);
#line 395
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Hello world!\n"END);
  __CrestClearStack(&*&544END);
  __CrestLoad(&*&545, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )5END);
  __CrestLoad(&*&546, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )2END);
#line 398
  tmp3588 = mult(&*&5, &*&2END);
  __CrestHandleReturn(&*&548, &*&(3322long long4176 )tmpEND);
  __CrestStore(&*&547, &*&(3322unsigned long4176 )(& tmp)END);
  __CrestLoad(&*&549, &*&(3322unsigned long4176 )(& tmp), &*&(3322long long4176 )tmpEND);
#line 398
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"mult %d \n", &*&tmpEND);
  __CrestClearStack(&*&550END);
  __CrestLoad(&*&551, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 400
  tmp___03588 = Type1a_Krawitz(&*&4END);
  __CrestClearStack(&*&552END);
#line 400
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Type1a_Krawitz: %lf \n",
            &*&tmp___0END);
  __CrestClearStack(&*&553END);
  __CrestLoad(&*&554, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 401
  tmp___13588 = Type1b_Krawitz(&*&4END);
  __CrestClearStack(&*&555END);
#line 401
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Type1b_Krawitz: %lf \n",
            &*&tmp___1END);
  __CrestClearStack(&*&556END);
  __CrestLoad(&*&557, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 402
  tmp___23588 = Type2a_Krawitz(&*&4END);
  __CrestClearStack(&*&558END);
#line 402
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Type2a_Krawitz: %lf \n",
            &*&tmp___2END);
  __CrestClearStack(&*&559END);
  __CrestLoad(&*&560, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 403
  tmp___33588 = Type2b_Krawitz(&*&4END);
  __CrestClearStack(&*&561END);
#line 403
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Type2b_Krawitz: %lf \n",
            &*&tmp___3END);
  __CrestClearStack(&*&562END);
  __CrestLoad(&*&563, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 404
  tmp___43588 = Type3a_Krawitz(&*&4END);
  __CrestClearStack(&*&564END);
#line 404
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Type3a_Krawitz: %lf \n",
            &*&tmp___4END);
  __CrestClearStack(&*&565END);
  __CrestLoad(&*&566, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 405
  tmp___53588 = Type3b_Krawitz(&*&4END);
  __CrestClearStack(&*&567END);
#line 405
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Type3b_Krawitz: %lf \n",
            &*&tmp___5END);
  __CrestClearStack(&*&568END);
  __CrestLoad(&*&569, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 406
  tmp___63588 = Type4a_Krawitz(&*&4END);
  __CrestClearStack(&*&570END);
#line 406
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Type4a_Krawitz: %lf \n",
            &*&tmp___6END);
  __CrestClearStack(&*&571END);
  __CrestLoad(&*&572, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 407
  tmp___73588 = Type4b_Krawitz(&*&4END);
  __CrestClearStack(&*&573END);
#line 407
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Type4b_Krawitz: %lf \n",
            &*&tmp___7END);
  __CrestClearStack(&*&574END);
  __CrestLoad(&*&575, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )((3322char4176 )'-')END);
  __CrestLoad(&*&576, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )3END);
  __CrestLoad(&*&577, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 408
  tmp___83588 = Type4b2_Krawitz(&*&(3322char4176 )'-', &*&3, &*&3.0, &*&4END);
  __CrestClearStack(&*&578END);
#line 408
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"Type4b2_Krawitz: %lf \n",
            &*&tmp___8END);
  __CrestClearStack(&*&579END);
#line 410
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProdO_Cordy: %lf "END);
  __CrestClearStack(&*&580END);
  __CrestLoad(&*&581, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 411
  sumProdO(&*&4END);
  __CrestClearStack(&*&582END);
#line 412
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd1A_Cordy: %lf "END);
  __CrestClearStack(&*&583END);
  __CrestLoad(&*&584, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 413
  sumProd1A(&*&4END);
  __CrestClearStack(&*&585END);
#line 414
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd1B_Cordy: %lf "END);
  __CrestClearStack(&*&586END);
  __CrestLoad(&*&587, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 415
  sumProd1B(&*&4END);
  __CrestClearStack(&*&588END);
#line 416
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd1C_Cordy: %lf "END);
  __CrestClearStack(&*&589END);
  __CrestLoad(&*&590, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 417
  sumProd1C(&*&4END);
  __CrestClearStack(&*&591END);
#line 418
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd2A_Cordy: %lf "END);
  __CrestClearStack(&*&592END);
  __CrestLoad(&*&593, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 419
  sumProd2A(&*&4END);
  __CrestClearStack(&*&594END);
#line 420
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd2B_Cordy: %lf "END);
  __CrestClearStack(&*&595END);
  __CrestLoad(&*&596, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 421
  sumProd2B(&*&4END);
  __CrestClearStack(&*&597END);
#line 422
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd2C_Cordy: %lf "END);
  __CrestClearStack(&*&598END);
  __CrestLoad(&*&599, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 423
  sumProd2C(&*&4END);
  __CrestClearStack(&*&600END);
#line 424
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd2D_Cordy: %lf "END);
  __CrestClearStack(&*&601END);
  __CrestLoad(&*&602, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 425
  sumProd2D(&*&4END);
  __CrestClearStack(&*&603END);
#line 426
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd3A_Cordy: %lf "END);
  __CrestClearStack(&*&604END);
  __CrestLoad(&*&605, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 427
  sumProd3A(&*&4END);
  __CrestClearStack(&*&606END);
#line 428
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd3B_Cordy: %lf "END);
  __CrestClearStack(&*&607END);
  __CrestLoad(&*&608, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 429
  sumProd3B(&*&4END);
  __CrestClearStack(&*&609END);
#line 430
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd3C_Cordy: %lf "END);
  __CrestClearStack(&*&610END);
  __CrestLoad(&*&611, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 431
  sumProd3C(&*&4END);
  __CrestClearStack(&*&612END);
#line 432
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd3D_Cordy: %lf "END);
  __CrestClearStack(&*&613END);
  __CrestLoad(&*&614, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 433
  sumProd3D(&*&4END);
  __CrestClearStack(&*&615END);
#line 434
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd3E_Cordy: %lf "END);
  __CrestClearStack(&*&616END);
  __CrestLoad(&*&617, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 435
  sumProd3E(&*&4END);
  __CrestClearStack(&*&618END);
#line 436
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd4A_Cordy: %lf "END);
  __CrestClearStack(&*&619END);
  __CrestLoad(&*&620, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 437
  sumProd4A(&*&4END);
  __CrestClearStack(&*&621END);
#line 438
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd4B_Cordy: %lf "END);
  __CrestClearStack(&*&622END);
  __CrestLoad(&*&623, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 439
  sumProd4B(&*&4END);
  __CrestClearStack(&*&624END);
#line 440
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd4C_Cordy: %lf "END);
  __CrestClearStack(&*&625END);
  __CrestLoad(&*&626, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 441
  sumProd4C(&*&4END);
  __CrestClearStack(&*&627END);
#line 442
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\nsumProd4D_Cordy: %lf "END);
  __CrestClearStack(&*&628END);
  __CrestLoad(&*&629, &*&(3322unsigned long4176 )0, &*&(3322long long4176 )4END);
#line 443
  sumProd4D(&*&4END);
  __CrestClearStack(&*&630END);
#line 453
  printf(&*&(3322char const4461  4176 *4212 __restrict4461  )"\n\n\n\n\n\n\n\n"END);
  __CrestClearStack(&*&631END);
#line 454
  system(&*&"pause"END);
  __CrestClearStack(&*&632END);
  {
  __CrestReturn(&*&633END);
#line 393
  return;
  }
}
}

void4168 ^^sfn^^: __globinit_kraw_try1__globinit_kraw_try1^^efn^^
__globinit_kraw_try1(4248void)
{ DANSTART

  {
  __CrestInit(&*&END);
}
}
